#
# WebsiteBundle
#
# DefaultController

rclab_website_home:
    path:     /
    defaults: { _controller: RCLABWebsiteBundle:Default:index }

rclab_website_contact:
    path:     /contact
    defaults:  { _controller: RCLABWebsiteBundle:Default:contact }

rclab_website_association:
    path:     /association
    defaults:  { _controller: RCLABWebsiteBundle:Default:association }

rclab_website_reparation:
    path:     /reparation
    defaults:  { _controller: RCLABWebsiteBundle:Default:reparation }

rclab_website_cours:
    path:     /cours
    defaults:  { _controller: RCLABWebsiteBundle:Default:cours }

rclab_website_compte:
    path:    /compte
    defaults:  { _controller: RCLABWebsiteBundle:Default:compte }


# ActualiteController

rclab_website_actualite:
    path:     /actualite
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:actualite

# news
rclab_website_actualite_news:
    path:    /actualite/news/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:news
        page:        1
    requirements:
        page:    \d+

rclab_website_actualite_news_detail:
    path:    /actualite/news/news/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:newsDetail
    requirements:
        id:    \d+

rclab_website_actualite_news_add:
    path:    /actualite/news/add
    defaults: { _controller: RCLABWebsiteBundle:Actualite:addNews }

rclab_website_actualite_news_edit:
    path:    /actualite/news/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:editNews
    requirements:
        id:     \d+

rclab_website_actualite_news_remove:
    path:    /actualite/news/remove/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:removeNews
    requirements:
        id:    \d+

# events
rclab_website_actualite_events:
    path:    /actualite/events/{page}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:events
        page:        1
    requirements:
        page:    \d+

rclab_website_actualite_events_detail:
    path:    /actualite/events/event/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:eventDetail
    requirements:
        id:    \d+

rclab_website_actualite_events_add:
        path:    /actualite/events/add
        defaults: { _controller: RCLABWebsiteBundle:Actualite:addEvent }


rclab_website_actualite_events_edit:
    path:    /actualite/events/edit/{id}
    defaults:
        _controller: RCLABWebsiteBundle:Actualite:editEvent


rclab_website_actualite_events_remove:
    path:    /actualite/events/remove/{id}
    defaults:
         _controller: RCLABWebsiteBundle:Actualite:removeEvent
    requirements:
        id:    \d+

#
# UserBundle
#

# RegistrationController

rclab_user_registration_register:
    path:    /inscription
    defaults: { _controller: RCLABUserBundle:Registration:register }

rclab_user_registration_checkEmail:
    path:    /inscription/verification/{id}
    defaults: { _controller: RCLABUserBundle:Registration:checkEmail }

#
# FosUserBundle
#

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile